# Pra rodar Local no senac...
services:

  emissor-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: emissor-service
    ports:
      - "8081:8081"
    networks:
      - rede_prova
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

networks:
  rede_prova:
      external: true