# Pra rodar Local no senac...
services:

  emissor-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: emissor-service
    ports:
      - "8081:8081"
    networks:
      - rede_prova

networks:
  rede_prova:
      external:
         name: rede_prova